### ISSUE TITLE
version `GLIBC_2.35' not found (required by /snap/dvc/1449/bin/python3)

### ISSUE THREAD

**Issue by amarburg** [iterative/dvc-snap#200]
On an up-to-date Ubuntu 20.04.06 installation (pinned to 20.04 because we are using ROS1), my snap automatically updated from DVC 3.42.00 / revision 1448 to DVC 3.44.0 / revision 1449.   Any `dvc` command now produces:

```
$ dvc
/snap/dvc/1449/bin/python3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /snap/dvc/1449/bin/python3)
/snap/dvc/1449/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/dvc/1449/bin/python3)
/snap/dvc/1449/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /snap/dvc/1449/bin/python3)
/snap/dvc/1449/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/dvc/1449/bin/python3)
```

The currently installed `libc-*` packages are `2.31-0ubuntu9.14`

The problem is resolvable by rolling back to 3.42.00 (`sudo snap revert dvc --revision 1448`), and repeatable by manually rolling forward to 3.44.0

**Comment by efiop** [comment]
@amarburg Thank you for reporting this! I've revered my change and found another way to fix builds for now.

Unfortunately I don't quite remember if snap allows updates for packages with the same version, so you might have to wait for a new dvc version release (likely no more than a week).

**Comment by efiop** [comment]
@amarburg Looks like snap does allow updating the same version, so a fixed package is up now. Please feel free to give it a try. Thanks again for the feedback.

**Comment by amarburg** [comment]
Just confirming, I was auto-upgraded to dvc 3.44.0 / revision 1452 and it's working.  Thanks!
