### ISSUE TITLE
Linux install with snap

### ISSUE THREAD

**Issue by dacbd** [iterative/dvc-snap#38]
link: https://dvc.org/doc/install/linux#install-with-snap

The additional flags `--beta` and `--edge` result in messages: 
- `Channel latest/beta for dvc is closed; temporarily forwarding to stable.`
- `Channel latest/edge for dvc is closed; temporarily forwarding to stable.`

- [x] Should mention of these flags remain if they are closed?

**Comment by efiop** [comment]
Transfered to dvc-snap. Looks like we have snap builds breaking. 🙁 @casperdcl could you take a look, please?

**Comment by casperdcl** [comment]
Should be fixed now.

`2.9.5` is the first release since `2.8.1` from 4 months ago :sweat:

Had to do much battle :person_fencing: #39 :)
