### ISSUE TITLE
repro: PATH corrupted when running dvc repro

### ISSUE THREAD

**Issue by grutledge007** [iterative/dvc-snap#41]
# Bug Report

## Description

dvc repro fails on very simple commands that run fine from the command line due to a PATH corruption.

### Reproduce

1. echo $PATH
2. create a stage called test in your dvc.yaml file with cmd: echo $PATH
3. dvc repro test
4. compare the output from 1 and 3 and observe that all (or most) of the paths in 1 are removed in 3

### Expected

Expected the output of echo $PATH when run using dvc repro to match, or at least contain the same paths when echo $PATH is run at the command line.  
### Environment information

Note that this issue just started happening when I upgraded to DVC 2.9.5.  If I revert back to the version I was using previously (DVC 2.8.1), then I get the expected behavior and dvc repro works as expected.

**Output of `dvc doctor`:**
When dvc corrupts the PATH (in 2.9.5)
```console
$ dvc doctor
```
DVC version: 2.9.5 (snap)
---------------------------------
Platform: Python 3.8.10 on Linux-5.11.0-41-generic-x86_64-with-glibc2.29
Supports:
        azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2022.2.0),
        webhdfs (fsspec = 2022.2.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.2.0, boto3 = 1.20.24),
        ssh (sshfs = 2021.11.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: local
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

When dvc repro works properly (in 2.8.1)
```console
$ dvc doctor
```
DVC version: 2.8.1 (snap)
---------------------------------
Platform: Python 3.6.9 on Linux-5.11.0-41-generic-x86_64-with-Ubuntu-20.04-focal
Supports:
        azure (adlfs = 2021.9.1, knack = 0.8.2, azure-identity = 1.6.1),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2021.10.0),
        webhdfs (fsspec = 2021.10.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.10.0, boto3 = 1.17.106),
        ssh (sshfs = 2021.9.0)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: local
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
**Additional Information (if any):**

Here is the output of 
```console
$ echo $PATH
```
/home/grutledge/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/bin/remote-cli:/home/grutledge/.local/bin:/home/grutledge/.conda/envs/mlenv-dev/bin:/opt/miniconda3/condabin:/opt/miniconda3/condabin:/opt/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Here is the output of 
```console
$ dvc repro test --verbose
```
Notice that the path does not contain any of my conda paths that are present when I run echo $PATH from the command line, but instead contains just the paths associated with my snap dvc install.

2022-03-09 23:09:58,290 DEBUG: Assuming 'test' to be a stage inside 'dvc.yaml'
2022-03-09 23:09:58,369 DEBUG: stage: 'test' changed.
Running stage 'test':
> echo $PATH
/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/dvc/1321/usr/bin:/snap/dvc/1321/bin
2022-03-09 23:09:58,372 DEBUG: Computed stage: 'test' md5: '78aee6f44af5f3368c082696e7af4d46'
2022-03-09 23:09:58,373 DEBUG: stage: 'test' was reproduced
Use `dvc push` to send your updates to remote storage.
2022-03-09 23:09:58,396 DEBUG: Analytics is enabled.
2022-03-09 23:09:58,416 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp520_rqcd']'
2022-03-09 23:09:58,417 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp520_rqcd']'

**Comment by casperdcl** [comment]
Thanks for pinging me @pared.

:facepalm: bug introduced in #39

**Comment by efiop** [comment]
Thank you @casperdcl ! 🙏 ❤️

**Comment by grutledge007** [comment]
Thank you very much for addressing this issue @casperdcl and for everyone's attention on this matter!  I really appreciate it.
