### ISSUE TITLE
Does snap not install the DVC Python module?

### ISSUE THREAD

**Issue by haimat** [iterative/dvc-snap#99]
I have installed DVC via snap, which worked fine for the command line. However, it seems the DVC Python module has not been installed:

```bash
$ python -m dvc
/usr/bin/python: No module named dvc
```

Is this a bug or a feature, do I need to install DVC via `pip` as well?

**Comment by efiop** [comment]
snap installs dvc in an isolated enviroment, that's the purpose of snap. If you need to use dvc as a library - you'll indeed need to install through pip (or conda) in an env that you will be using it in.
